### PR TITLE
Add CLI application

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[build.gradle, line 62 at r3](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3#-MGPgthB-WInGeSZZb_E:-MGPgthB-WInGeSZZb_F:blstyvs) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/92e32cfc5a54ec2520292f4a148f163c39c3437b/build.gradle#L62)):*
> ```Gradle
> application {
>     mainClassName = "org.wycliffeassociates.resourcecontainer.media.MainKt"
> }
> ```

I'd separate this app into a different gradle project from the library.

Create the library project as a java-library, and have this one use it as a dependency.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/CIApplication.kt, line 19 at r3](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3#-MGPgDNs0YQw-KFGb9mg:-MGPgDNtAT7qHFy5cr_N:bw86d0y) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/92e32cfc5a54ec2520292f4a148f163c39c3437b/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/CIApplication.kt#L19)):*
> ```Kotlin
> 
>     private val projectId by option(
>         "-pi", "--projectid",
> ```

why not "-id"

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[build.gradle, line 62 at r3](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3#-MGPgthB-WInGeSZZb_E:-MGi8Hi4BF7JknVxjg-n:b-896fix) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/92e32cfc5a54ec2520292f4a148f163c39c3437b/build.gradle#L62)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I'd separate this app into a different gradle project from the library.

Create the library project as a java-library, and have this one use it as a dependency.
</blockquote></details>

Done.

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @16dprice and @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/CIApplication.kt, line 19 at r3](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3#-MGPgDNs0YQw-KFGb9mg:-MGi8L3RBS0BNNrPjq_F:b-ptsbla) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/92e32cfc5a54ec2520292f4a148f163c39c3437b/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/CIApplication.kt#L19)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why not "-id"
</blockquote></details>

I think it could be confused with different identifiers in the RC, couldn't it?

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/3#-:-MGiIvEu8ExtnwzqT3XY:bnfp4nl)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @16dprice and @jsarabia)

**Pull request merged**
