### PR TITLE
Download Module + retrofit client downloader

### PR DESCRIPTION
**Pull request by AnonymousWalker**
This is ready to review

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2)

### CODE REVIEW

**Review by 16dprice — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 13 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDpBwI3KFkN8EjxNLl:-MGDpBwI3KFkN8EjxNLm:b-sdxxdh) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L13)):*
> ```Kotlin
> class RCMediaDownloader private constructor(
>     rcFile: File,
>     overwrite: Boolean,
> ```

I think this Boolean should be optional so that it doesn't have to be passed. If we want to optionally overwrite the file, then it makes sense to have this an optional parameter, I think. Not sure what the default value should be, maybe false since the user may not usually care about whether it's getting overwritten? I believe that was Joe's original expectation, but I could be wrong.

It should be moved to be the third parameter as well if it's going to be optional.

By the way, I know that this is a private constructor and that it will probably only be called from the companion object of this class, but I still think it's best to have the constructor line up with the function that's calling it. I think it makes the code more readable.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 45 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDqFLA3KNXsa3MZCGQ:-MGDqFLBDpzrrslMoEDT:b-o9cgfr) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L45)):*
> ```Kotlin
>         }
> 
>         if (mediaProject != null) {
> ```

I would probably replace with if(mediaProject == null) { return rcOutputFile }

That would then take out a level of nesting in the function and make it clearer to anyone reading the code that if the mediaProject is null, then there is nothing else we want to do in this function. I had to read through the whole thing to find out what happened when mediaProject is null.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 66 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDqaVx5kZTTLcVZNvF:-MGDqaVx5kZTTLcVZNvG:b-i93zra) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L66)):*
> ```Kotlin
>     }
> 
>     // download a project
> ```

I think this comment is unnecessary. The function name says the same thing.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 82 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDqe_D9O6EFVtIrwa_:-MGDqe_D9O6EFVtIrwaa:b-i93zra) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L82)):*
> ```Kotlin
>     }
> 
>     // download all chapters
> ```

I think this comment is unnecessary. The function name says the same thing.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 97 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDquJ4DKHKnBPSfXDc:-MGDquJ4DKHKnBPSfXDd:boyypbg) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L97)):*
> ```Kotlin
>             val downloadedFile = downloadWithClient(downloadUrl, contentDir)
>             if (downloadedFile != null) {
>                 // add file to container
> ```

This comment is inaccurate. This isn't adding anything to the container yet.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 120 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDrGPU8Bl2bt60zyZl:-MGDrGPU8Bl2bt60zyZm:b-bz8gn9) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L120)):*
> ```Kotlin
> 
>         val call = downloader.downloadFile(urlFile.name)
>         val response = call.execute()
> ```

I would add a newline after this line. And maybe delete one or both of the newlines before this so that the variable declarations are separated from the code if statement.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 152 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDrV1fD5lzllWkKWlH:-MGDrV1fD5lzllWkKWlI:bnn9vma) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L152)):*
> ```Kotlin
>             }
>         }
>         return outputFile
> ```

Newline before this line is my personal preference but it doesn't really matter to me.

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 13 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDpBwI3KFkN8EjxNLl:-MGDsYzr9yAz3ZirKaTS:b-vs59k6) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L13)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

I think this Boolean should be optional so that it doesn't have to be passed. If we want to optionally overwrite the file, then it makes sense to have this an optional parameter, I think. Not sure what the default value should be, maybe false since the user may not usually care about whether it's getting overwritten? I believe that was Joe's original expectation, but I could be wrong.

It should be moved to be the third parameter as well if it's going to be optional.

By the way, I know that this is a private constructor and that it will probably only be called from the companion object of this class, but I still think it's best to have the constructor line up with the function that's calling it. I think it makes the code more readable.
</blockquote></details>

The optional parameter came from the public static function download(), which given the value to pass into the private constructor.

**Comment by AnonymousWalker** [comment]
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 45 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDqFLA3KNXsa3MZCGQ:-MGDu2ZT5XMyLg2OQjGW:b-joddjj) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L45)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

I would probably replace with if(mediaProject == null) { return rcOutputFile }

That would then take out a level of nesting in the function and make it clearer to anyone reading the code that if the mediaProject is null, then there is nothing else we want to do in this function. I had to read through the whole thing to find out what happened when mediaProject is null.
</blockquote></details>

sounds good to me

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @16dprice and @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 66 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDqaVx5kZTTLcVZNvF:-MGDunvS55YwxAkNOFqF:b2nhswv) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L66)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

I think this comment is unnecessary. The function name says the same thing.
</blockquote></details>

Yep
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 82 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDqe_D9O6EFVtIrwa_:-MGDurl99eLfBQe3pSdj:b2nhswv) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L82)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

I think this comment is unnecessary. The function name says the same thing.
</blockquote></details>

Yep
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 97 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDquJ4DKHKnBPSfXDc:-MGDvW_59c6IUp6kdhDw:b-who1vt) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L97)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

This comment is inaccurate. This isn't adding anything to the container yet.
</blockquote></details>

yeah it was deprecated
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 120 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDrGPU8Bl2bt60zyZl:-MGDvdfA0xONwkT1nHzx:b-896fix) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L120)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

I would add a newline after this line. And maybe delete one or both of the newlines before this so that the variable declarations are separated from the code if statement.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 152 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDrV1fD5lzllWkKWlH:-MGDviQj0f-9rzgiahdJ:b2f80dj) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L152)):*
<details><summary><i>Previously, 16dprice wrote…</i></summary><blockquote>

Newline before this line is my personal preference but it doesn't really matter to me.
</blockquote></details>

I think it's readable without a new line anyway...

**Review by 16dprice — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @16dprice, @AnonymousWalker, and @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 13 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDpBwI3KFkN8EjxNLl:-MGDwuIH6g2u8m2VGtHg:b6tfjok) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L13)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

The optional parameter came from the public static function download(), which given the value to pass into the private constructor. 
</blockquote></details>

I just think it's more consistent to make the constructor have the optional param as well. Because when someone reads the code, they will see that the overwrite variable is optional and understand that it need not be passed to whatever uses this. I know they'll be calling this by using the download function, but that doesn't mean that we should make the concept of overwriting be more opaque by implying that it's required in the class constructor.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 152 at r1](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGDrV1fD5lzllWkKWlH:-MGDxdd_Aur3EQH3RR7D:bntqg5f) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/c7ab2ab055dda77fbbf37b0957306599296f6264/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L152)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I think it's readable without a new line anyway...
</blockquote></details>

Sure, that's fine with me.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 2 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/BookMediaDownloader.kt, line 14 at r5](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGJT4347FJROwx9E4EH:-MGJT4347FJROwx9E4EI:b-e41bj5) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/51da2ac166800e3c6eebf3acc927ca574c117c37/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/BookMediaDownloader.kt#L14)):*
> ```Kotlin
> ) : RCMediaDownloader(rcFile, overwrite, urlParams) {
> 
>     override fun execute(): File {
> ```

This code is exactly the same with the exception of one line in ChapterMediaDownloader.

This should be rewritten in order to put this code in the abstract class.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 24 at r3](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGJ26tI5JF4oYEf5jw_:-MGJ26tJBAEwjb0F_9dH:brhifz2) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/94484d4ed89b17b5f33a521053269e5219961fea/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L24)):*
> ```Kotlin
>     private val rc = ResourceContainer.load(rcOutputFile)
> 
>     companion object {
> ```

please move the companion object to the bottom of the class:

https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout

**Review by AnonymousWalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/BookMediaDownloader.kt, line 14 at r5](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGJT4347FJROwx9E4EH:-MGJ_mfiDi6P-yXTqHCf:b-896fix) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/51da2ac166800e3c6eebf3acc927ca574c117c37/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/BookMediaDownloader.kt#L14)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This code is exactly the same with the exception of one line in ChapterMediaDownloader.

This should be rewritten in order to put this code in the abstract class.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt, line 24 at r3](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-MGJ26tI5JF4oYEf5jw_:-MGJ_nMJ2MYjH6LZa1xQ:b-896fix) ([raw file](https://github.com/wycliffeassociates/rc_mediadownloader/blob/94484d4ed89b17b5f33a521053269e5219961fea/src/main/kotlin/org/wycliffeassociates/resourcecontainer/media/RCMediaDownloader.kt#L24)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

please move the companion object to the bottom of the class:

https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/rc_mediadownloader/2#-:-MGK2tPxCq7Xnp7fIVNr:bnfp4nl)* status: 4 of 11 files reviewed, all discussions resolved (waiting on @jsarabia)

**Pull request merged**
